app = "university-doc-system"
primary_region = "sin"  # Singapore region, can be changed as needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  UPLOAD_FOLDER = "uploads"
  MAX_CONTENT_LENGTH = "16777216"
  MAIL_SERVER = "smtp.gmail.com"
  MAIL_PORT = "587"
  MAIL_USE_TLS = "True"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "uploads"
  destination = "/app/app/uploads"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "flask db upgrade"

[services]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
