services:
  - type: web
    name: edusync
    runtime: python
    region: frankfurt
    plan: starter
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y libmagic1
      pip install -r requirements.txt
      # Initialize database
      flask db upgrade
    startCommand: gunicorn run:app --worker-class=uvicorn.workers.UvicornWorker --workers=4 --bind=0.0.0.0:$PORT --timeout=120 --log-level=info
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false  # Will be set manually from Neon
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: "20971520"
      - key: GUNICORN_TIMEOUT
        value: "120"
      - key: GUNICORN_LOG_LEVEL
        value: "info"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
