services:
  - type: web
    name: edusync
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --workers 4 --threads 2 --worker-class aiohttp.worker.GunicornWebWorker --timeout 120 --access-logfile - --error-logfile -
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: SERVER_NAME
        value: edusync.onrender.com
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
