services:
  - type: web
    name: edusync
    runtime: python
    region: singapore
    plan: starter
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y libmagic1
      pip install -r requirements.txt
      # Initialize database
      flask db upgrade
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker run:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false  # Will be set manually from Neon
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216" # 16MB max file size
      - key: GUNICORN_WORKERS
        value: "4"
      - key: GUNICORN_TIMEOUT
        value: "120"
      - key: PATH
        value: /opt/render/project/src/uploads:${PATH}
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
