services:
  - type: web
    name: edusync
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      pip install psycopg2-binary
    startCommand: |
      export FLASK_APP=run.py
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      flask db upgrade
      mkdir -p uploads
      gunicorn --config gunicorn.conf.py wsgi:app
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SESSION_TYPE
        value: redis
      - key: SESSION_PERMANENT
        value: "true"
      - key: PERMANENT_SESSION_LIFETIME
        value: "86400"
      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_TIMEOUT
        value: "60"
      # Secret values should be set in Render dashboard
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: edusync-db
          property: connectionString
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

    healthCheckPath: /
    autoDeploy: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: edusync-db
    databaseName: edusync
    plan: free
    region: oregon
