"""Add Google Drive fields to Document model

Revision ID: 0c54c548cc57
Revises: 3060e60cf56b
Create Date: 2025-02-28 18:02:08.938157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c54c548cc57'
down_revision = '3060e60cf56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gdrive_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gdrive_view_link', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('gdrive_review1_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gdrive_review2_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gdrive_review1_link', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('gdrive_review2_link', sa.String(length=512), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('gdrive_review2_link')
        batch_op.drop_column('gdrive_review1_link')
        batch_op.drop_column('gdrive_review2_id')
        batch_op.drop_column('gdrive_review1_id')
        batch_op.drop_column('gdrive_view_link')
        batch_op.drop_column('gdrive_file_id')

    # ### end Alembic commands ###
